### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by SyumSenpai** [Haidra-Org/horde-worker-reGen#167]
critical libmamba Cannot activate, prefix does not exist at: 'C:\Users\yuuwa\OneDrive\Plocha\horde-worker-reGen-main\conda\envs\windows'

ERROR: Cannot install -r requirements.txt (line 5) because these package versions have conflicting dependencies.

The conflict is caused by:
    hordelib 2.6.5 depends on mediapipe>=0.9.1.0
    hordelib 2.6.4 depends on mediapipe>=0.9.1.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

i try lot of stuff but non of them help me

**Comment by tazlin** [comment]
We can best help you in the discord (https://discord.com/channels/781145214752129095/1076124012305993768). 

If you aren't able to come to discord, try deleting the `conda` folder, re-running `update-runtime.cmd` and trying again.

**Comment by SyumSenpai** [comment]
okay

**Comment by SyumSenpai** [comment]
okay
