### ISSUE TITLE
Incorrect Batch index and another problem/situation

### ISSUE THREAD

**Issue by arcaria** [Haidra-Org/horde-worker-reGen#242]
First, the batch index thing
I noticed that if you send the exact same payload multiple times, requesting x number of images, say 5 (as in my tests), the same image will not have the same batch_index in all the requests.
In tazlin's words: "Then that’s probably a bug... you’re saying that the same image has a mismatched batch index during subsequent runs?"
link to the conversation on discord: https://discord.com/channels/781145214752129095/1081743238194536458/1267960076560371722

Second, the weird situation I encountered
When testing the above (batch_index not matching), I got a result back where the images were generally the same as the previous result (same exact payload) but there were some differences across matching pairs of images (some images were more different than others)
Example where both images (same payload/2 different runs/same worker-db0's) are nearly identical, but there are some differences here and there.
![first](https://github.com/user-attachments/assets/7f3ed5db-d4d7-42c4-a47c-f01720c8a584)
![second](https://github.com/user-attachments/assets/46387d65-2797-4005-945c-1aa8131fc4be)

**Comment by tazlin** [comment]
Closed via #293.
