### ISSUE TITLE
I can't get “horde-bridge.cmd” to run.

### ISSUE THREAD

**Issue by pidori-ne-poluchat-parol** [Haidra-Org/horde-worker-reGen#366]
I can't get “horde-bridge.cmd” to run. I have a Windows 11 operating system.

This error is displayed at startup:
![image](https://github.com/user-attachments/assets/1ccbe6b9-43a3-44d6-a352-383004c1915c)

**Comment by tazlin** [comment]
This error relates to the installer (update-runtime.cmd) not having worked correctly. I have a few questions:

- Did you only recently download the worker or have you run the worker in the past?
  - if you downloaded it in the past, be sure to run `git pull`
- Do you have an install of Anaconda on your system?
- Can you try deleting the `conda` folder and running `update-runtime.cmd`?

**Comment by pidori-ne-poluchat-parol** [comment]
> This error relates to the installer (update-runtime.cmd) not having worked correctly. I have a few questions:
> 
> * Did you only recently download the worker or have you run the worker in the past? 
>   * if you downloaded it in the past, be sure to run `git pull`
> * Do you have an install of Anaconda on your system?
> * Can you try deleting the `conda` folder and running `update-runtime.cmd`?

1) First time running it. According to the instructions, I first ran update-runtime.cmd and then horde-bridge.cmd.
2) No. Thought it would install it on its own. Now I'll try to manually install it and try again
3) Yeah, I'm going to try that now and do what I wanted to do in 2)

**Comment by pidori-ne-poluchat-parol** [comment]
> Для ясности: вам не нужна Anaconda, я спросил только потому, что она может вызывать подобные конфликты

Got it, I've now deleted conda and am updating it.
![image](https://github.com/user-attachments/assets/305739b2-f537-4e70-ba28-0b0b41fdfd39)

**Comment by pidori-ne-poluchat-parol** [comment]
It gave several errors and one error that I forgot to write about.
Here are the errors during the update:
![image](https://github.com/user-attachments/assets/bcb2abb0-7f71-4106-b758-eb04ef19489c)
![image](https://github.com/user-attachments/assets/cc19a194-abff-4075-b3e1-6346aaf0cb60)

Here is the final error:
![image](https://github.com/user-attachments/assets/5837deb6-b445-4254-9a94-f50a55d3af65)

**Comment by tazlin** [comment]
We could probably go back and forth on this for quite a while. I have seen issues like this before, but troubleshooting them usually requires quite a lot of time, and the technical skill required to nail it down is greater than installing the worker through other methods.

My suggestion is to
- delete the `conda/` directory
- install python 3.11 either through [their website](https://www.python.org/downloads/release/python-3110/) or through the microsoft/windows store, 
- follow [these alternative instructions for installing the worker](https://github.com/Haidra-Org/horde-worker-reGen/blob/main/README_advanced.md#advanced-users-local-install).

Also, we could more interactively troubleshoot and additional people could chime in if you come to the [discord server](https://discord.gg/3DxrhksKzn) (the #local-workers channel). If not, I'll do my best to assist you here.

**Comment by pidori-ne-poluchat-parol** [comment]
> We could probably go back and forth on this for quite a while. I have seen issues like this before, but troubleshooting them usually requires quite a lot of time, and the technical skill required to nail it down is greater than installing the worker through other methods.
> 
> My suggestion is to
> 
> * delete the `conda/` directory
> * install python 3.11 either through [their website](https://www.python.org/downloads/release/python-3110/) or through the microsoft/windows store,
> * follow [these alternative instructions for installing the worker](https://github.com/Haidra-Org/horde-worker-reGen/blob/main/README_advanced.md#advanced-users-local-install).
> 
> Also, we could more interactively troubleshoot and additional people could chime in if you come to the [discord server](https://discord.gg/3DxrhksKzn) (the #local-workers channel). If not, I'll do my best to assist you here.

In that case, I'll try to follow the alternative instructions for installing the worker. If that doesn't work, I will ask you for help on that Discord server

**Comment by pidori-ne-poluchat-parol** [comment]
Bottom line: I didn't have https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170&wt.mc_id=studentamb_203301#latest-microsoft-visual-c-redistributable-version installed because I recently formatted my PC
