### ISSUE TITLE
Add setting which will trigger unused lora purge on a timer

### ISSUE THREAD

**Issue by db0** [Haidra-Org/horde-worker-reGen#367]
It used to be the default but was disabled with regen. We should add it back with a bridgeData boolean

**Comment by tazlin** [comment]
There is already an option that does this https://github.com/Haidra-Org/horde-worker-reGen/blob/e936e5d1f218272321dbbfeeb8493d1b07d6480b/bridgeData_template.yaml#L176. If its implemented wrong, feel free to re-open.
