### ISSUE TITLE
download models doesn't re-download new versions of models

### ISSUE THREAD

**Issue by db0** [Haidra-Org/horde-worker-reGen#84]
If a new version of the model was added to the reference, the download script doesn't compare sha256 to redownload it.

**Comment by tazlin** [comment]
Fixed on the niter branch

**Comment by tazlin** [comment]
If you are willing/able, confirm the changes work as intended and feel free to merge in https://github.com/Haidra-Org/horde-worker-reGen/pull/85. I am unavailable to check this right now.
