### ISSUE TITLE
`horde-bridge` script proceeds to start worker even if downloads fail

### ISSUE THREAD

**Issue by tazlin** [Haidra-Org/horde-worker-reGen#92]
While SD models are not a huge problem, control nets and upscalers being missing would cause runtime problems.

**Comment by db0** [comment]
I send a new change to the niter branch to handle this. Can you test on windows? On linux it's OK

**Comment by CIB** [comment]
It is also a problem for SD models, as for some reason it will try to pop jobs with the model that failed to download. It'd also be nice if the "top N models" command would exclude models that require an API key, if no API key is specified.

**Comment by arcaria** [comment]
@tazlin @db0
Why not just hardcode an API key into the worker when none is specified by the user?
The workers do not currently inform the users why a lora failed to download, only that it did

**Comment by tazlin** [comment]
> @tazlin @db0
> 
> Why not just hardcode an API key into the worker when none is specified by the user?
> 
> The workers do not currently inform the users why a lora failed to download, only that it did

Sharing accounts is explicitly against the CivitAI terms of service and they have greatly expanded their crackdown on requiring logins lately. Committing tokens or password to a git rep is a very bad practice at best and at worst would constitute a flagrant ToS violation would could lead to some sort of drastic action on their part.


As for the better communication of the reason to end users, we could look into that.
